#!/usr/bin/env bash
# Dorothy Command: setup-util-claude
# Purpose: Install GSD2-pi CLI / Desktop

NODE_VERSION=$(node --version)
if ! [[ $NODE_VERSION =~ ^v22\. ]]; then
	echo "Requires Node 22 (Found: $NODE_VERSION)"
	exit 1
fi
SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install -g gsd-pi@latest

curl -fsSL https://raw.githubusercontent.com/JuliusBrussee/caveman/main/install.sh | bash
curl -fsSL https://raw.githubusercontent.com/njbrake/agent-of-empires/main/scripts/install.sh | bash
uv tool install "headroom-ai[all]"
uv tool install serena-agent@latest --prerelease=allow # had -p 3.13
curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/DeusData/codebase-memory-mcp/main/scripts/setup.sh | bash
